# Generated by Django 4.2.29 on 2026-03-28 15:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('doctor', 'Médecin'), ('patient', 'Patient')], default='patient', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^\\+?[0-9]{9,15}$')], verbose_name='Téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Lien URL')),
                ('link_text', models.CharField(blank=True, default='En savoir plus', max_length=100, verbose_name='Texte du bouton')),
                ('position', models.CharField(choices=[('hero', 'Bannière principale (Hero)'), ('top', 'En haut de page'), ('sidebar', 'Barre latérale'), ('bottom', 'Bas de page')], default='top', max_length=20, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('background_color', models.CharField(default='#f0f7ff', max_length=20, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#1e3a5f', max_length=20, verbose_name='Couleur du texte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, verbose_name='Antécédents médicaux')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('wilaya', models.CharField(blank=True, choices=[('01', '01 - Adrar'), ('02', '02 - Chlef'), ('03', '03 - Laghouat'), ('04', '04 - Oum El Bouaghi'), ('05', '05 - Batna'), ('06', '06 - Béjaïa'), ('07', '07 - Biskra'), ('08', '08 - Béchar'), ('09', '09 - Blida'), ('10', '10 - Bouira'), ('11', '11 - Tamanrasset'), ('12', '12 - Tébessa'), ('13', '13 - Tlemcen'), ('14', '14 - Tiaret'), ('15', '15 - Tizi Ouzou'), ('16', '16 - Alger'), ('17', '17 - Djelfa'), ('18', '18 - Jijel'), ('19', '19 - Sétif'), ('20', '20 - Saïda'), ('21', '21 - Skikda'), ('22', '22 - Sidi Bel Abbès'), ('23', '23 - Annaba'), ('24', '24 - Guelma'), ('25', '25 - Constantine'), ('26', '26 - Médéa'), ('27', '27 - Mostaganem'), ('28', "28 - M'Sila"), ('29', '29 - Mascara'), ('30', '30 - Ouargla'), ('31', '31 - Oran'), ('32', '32 - El Bayadh'), ('33', '33 - Illizi'), ('34', '34 - Bordj Bou Arréridj'), ('35', '35 - Boumerdès'), ('36', '36 - El Tarf'), ('37', '37 - Tindouf'), ('38', '38 - Tissemsilt'), ('39', '39 - El Oued'), ('40', '40 - Khenchela'), ('41', '41 - Souk Ahras'), ('42', '42 - Tipaza'), ('43', '43 - Mila'), ('44', '44 - Aïn Defla'), ('45', '45 - Naâma'), ('46', '46 - Aïn Témouchent'), ('47', '47 - Ghardaïa'), ('48', '48 - Relizane'), ('49', '49 - Timimoun'), ('50', '50 - Bordj Badji Mokhtar'), ('51', '51 - Ouled Djellal'), ('52', '52 - Béni Abbès'), ('53', '53 - In Salah'), ('54', '54 - In Guezzam'), ('55', '55 - Touggourt'), ('56', '56 - Djanet'), ('57', "57 - El M'Ghair"), ('58', '58 - El Meniaa'), ('59', '59 - El Bayadh Nord'), ('60', '60 - Ain Témouchent Sud'), ('61', '61 - Relizane Nord'), ('62', '62 - Sig'), ('63', '63 - Mostaganem Est'), ('64', '64 - Oran Est'), ('65', '65 - Alger Ouest'), ('66', '66 - Alger Est'), ('67', '67 - Blida Nord'), ('68', '68 - Médéa Nord'), ('69', '69 - Boumerdès Nord')], max_length=3, verbose_name='Wilaya')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Patient',
                'verbose_name_plural': 'Profils Patients',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('generaliste', 'Médecin Généraliste'), ('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('neurologie', 'Neurologie'), ('orthopedie', 'Orthopédie'), ('pediatrie', 'Pédiatrie'), ('psychiatrie', 'Psychiatrie'), ('gynecologie', 'Gynécologie'), ('ophtalmologie', 'Ophtalmologie'), ('orl', 'ORL'), ('radiologie', 'Radiologie'), ('oncologie', 'Oncologie'), ('urologie', 'Urologie'), ('dentiste', 'Dentiste'), ('autre', 'Autre')], default='generaliste', max_length=50, verbose_name='Spécialisation')),
                ('wilaya', models.CharField(choices=[('01', '01 - Adrar'), ('02', '02 - Chlef'), ('03', '03 - Laghouat'), ('04', '04 - Oum El Bouaghi'), ('05', '05 - Batna'), ('06', '06 - Béjaïa'), ('07', '07 - Biskra'), ('08', '08 - Béchar'), ('09', '09 - Blida'), ('10', '10 - Bouira'), ('11', '11 - Tamanrasset'), ('12', '12 - Tébessa'), ('13', '13 - Tlemcen'), ('14', '14 - Tiaret'), ('15', '15 - Tizi Ouzou'), ('16', '16 - Alger'), ('17', '17 - Djelfa'), ('18', '18 - Jijel'), ('19', '19 - Sétif'), ('20', '20 - Saïda'), ('21', '21 - Skikda'), ('22', '22 - Sidi Bel Abbès'), ('23', '23 - Annaba'), ('24', '24 - Guelma'), ('25', '25 - Constantine'), ('26', '26 - Médéa'), ('27', '27 - Mostaganem'), ('28', "28 - M'Sila"), ('29', '29 - Mascara'), ('30', '30 - Ouargla'), ('31', '31 - Oran'), ('32', '32 - El Bayadh'), ('33', '33 - Illizi'), ('34', '34 - Bordj Bou Arréridj'), ('35', '35 - Boumerdès'), ('36', '36 - El Tarf'), ('37', '37 - Tindouf'), ('38', '38 - Tissemsilt'), ('39', '39 - El Oued'), ('40', '40 - Khenchela'), ('41', '41 - Souk Ahras'), ('42', '42 - Tipaza'), ('43', '43 - Mila'), ('44', '44 - Aïn Defla'), ('45', '45 - Naâma'), ('46', '46 - Aïn Témouchent'), ('47', '47 - Ghardaïa'), ('48', '48 - Relizane'), ('49', '49 - Timimoun'), ('50', '50 - Bordj Badji Mokhtar'), ('51', '51 - Ouled Djellal'), ('52', '52 - Béni Abbès'), ('53', '53 - In Salah'), ('54', '54 - In Guezzam'), ('55', '55 - Touggourt'), ('56', '56 - Djanet'), ('57', "57 - El M'Ghair"), ('58', '58 - El Meniaa'), ('59', '59 - El Bayadh Nord'), ('60', '60 - Ain Témouchent Sud'), ('61', '61 - Relizane Nord'), ('62', '62 - Sig'), ('63', '63 - Mostaganem Est'), ('64', '64 - Oran Est'), ('65', '65 - Alger Ouest'), ('66', '66 - Alger Est'), ('67', '67 - Blida Nord'), ('68', '68 - Médéa Nord'), ('69', '69 - Boumerdès Nord')], default='16', max_length=3, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tarif (DA)')),
                ('clinic_address', models.TextField(blank=True, verbose_name='Adresse du cabinet')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Médecin',
                'verbose_name_plural': 'Profils Médecins',
            },
        ),
    ]
