# Generated by Django 4.2.29 on 2026-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True, help_text='Vous pouvez mettre du texte ou un lien Google Maps (ex: https://maps.google.com/...)', verbose_name='Adresse du cabinet'),
        ),
    ]
