# Generated by Django 5.1.3 on 2026-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_doctorprofile_clinic_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="location_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Lien Google Maps"
            ),
        ),
    ]
