# Generated by Django 5.1.3 on 2026-04-06 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctorprofile_location_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("generaliste", "Médecin Généraliste - طب عام"),
                    ("cardiologie", "Cardiologie - أمراض القلب"),
                    ("dermatologie", "Dermatologie - أمراض الجلد"),
                    ("neurologie", "Neurologie - أمراض الأعصاب"),
                    ("orthopedie", "Orthopédie - جراحة العظام"),
                    ("pediatrie", "Pédiatrie - طب الأطفال"),
                    ("psychiatrie", "Psychiatrie - الطب النفسي"),
                    ("gynecologie", "Gynécologie - أمراض النساء والتوليد"),
                    ("ophtalmologie", "Ophtalmologie - أمراض العيون"),
                    ("orl", "ORL - أمراض الأنف والأذن والحنجرة"),
                    ("radiologie", "Radiologie - الأشعة والتصوير الطبي"),
                    ("oncologie", "Oncologie - علم الأورام"),
                    ("urologie", "Urologie - أمراض المسالك البولية"),
                    ("dentiste", "Dentiste - طب الأسنان"),
                    ("gastro", "Gastro-entérologie - أمراض الجهاز الهضمي والكبد"),
                    (
                        "endocrino",
                        "Endocrinologie - Diabétologie - الغدد الصماء والسكري",
                    ),
                    ("rhumato", "Rhumatologie - أمراض الروماتيزم والمفاصل"),
                    ("pneumo", "Pneumologie - الأمراض الصدرية والتنفسية"),
                    ("nephro", "Néphrologie - أمراض الكلى"),
                    ("chir_gen", "Chirurgie Générale - الجراحة العامة"),
                    ("med_interne", "Médecine Interne - الطب الباطني"),
                    ("nutrition", "Nutrition - التغذية العلاجية"),
                    ("psychologie", "Psychologie - الأخصائي النفسي"),
                    ("kine", "Kinésithérapie / Rééducation - التدليك والتأهيل الحركي"),
                    ("autre", "Autre - أخرى"),
                ],
                default="generaliste",
                max_length=50,
                verbose_name="Spécialisation",
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
