# Generated by Django 5.1.3 on 2026-04-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_doctorprofile_specialization_passwordresetotp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresetotp",
            options={"ordering": ["-created_at"], "verbose_name": "OTP Reset"},
        ),
        migrations.AlterField(
            model_name="passwordresetotp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
